- hosts: terraform-ansible
  tasks:
    - name: Criando o arquivo
      copy:
        dest: /home/ubuntu/index.html
        content: "<h1>Feito com terraform e ansible</h1>"

    - name: Criando o servidor
      shell: "nohup busybox httpd -f -p 8080 &"

    - name: Instalando o python3 e o virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes

    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/papp/venv
        name:
          - django
          - djangorestframework